# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  # - name: Research
  #   url: research/
  #   weight: 11
  - name: Teaching
    identifier: teaching
    url: teaching/
    weight: 12
  - name: Teaching Overview
    # parent: teaching
    url: teaching/teaching-overview
    weight: 13
  # - name: Teaching Philosophy
  #   # parent: teaching
  #   url: teaching/teaching-philosophy
  #   weight: 14
  - name: About
    url: about/
    weight: 20
